### ISSUE TITLE
Public key not installed?  

### ISSUE THREAD

**Issue by ghost** [oVirt/ovirt-ansible-repositories#7]
Hello there,

I tried to deploy oVirt on CentOS 7.4 via Ansible and basically did this : 

```yaml
---
- name: Déploiement d'un hyperviseur oVirt
  hosts: jupiter
  user: root
  roles:
    - role: oVirt.repositories
      ovirt_repositories_ovirt_release_rpm: 'http://resources.ovirt.org/pub/yum-repo/ovirt-release42.rpm'

    - role: oVirt.engine-setup
      ovirt_engine_setup_version: '4.2'
      ovirt_engine_setup_organization: 'of.ovirt.engine.com'
      ovirt_engine_setup_admin_password: "fakepassword"

  tasks:
    - name: Installation des mises à jour
      yum:
        name: "*"
        state: latest
...
```

However for reasons I do not understand, it just fails and give me this  : 

```
TASK [oVirt.repositories : Install oVirt release package] **********************************************************************************************************************
fatal: [jupiter]: FAILED! => {"changed": false, "msg": "warning: /tmp/ovirt-release42nBD5x3.rpm: Header V4 RSA/SHA1 Signature, key ID fe590cb7: NOKEY\n\n\nPublic key for ovirt-release42nBD5x3.rpm is not installed\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nExamining /tmp/ovirt-release42nBD5x3.rpm: ovirt-release42-4.2.1.1-1.el7.centos.noarch\nMarking /tmp/ovirt-release42nBD5x3.rpm to be installed\nResolving Dependencies\n--> Running transaction check\n---> Package ovirt-release42.noarch 0:4.2.1.1-1.el7.centos will be installed\n--> Finished Dependency Resolution\n--> Finding unneeded leftover dependencies\nFound and removing 0 unneeded dependencies\n\nDependencies Resolved\n\n================================================================================\n Package          Arch    Version                 Repository               Size\n================================================================================\nInstalling:\n ovirt-release42  noarch  4.2.1.1-1.el7.centos    /ovirt-release42nBD5x3   13 k\n\nTransaction Summary\n================================================================================\nInstall  1 Package\n\nTotal size: 13 k\nInstalled size: 13 k\nDownloading packages:\n"]}

```

Is this an expected behaviour ?

Thank you
